In [23]:
a = [4, 1, 0, 9, 6] # this is creating normal array that we know
print(a)  


array1 = np.array([2, 3, 1,])  # creating array using np method 
print(array1)


[4, 1, 0, 9, 6]
[2 3 1]


In [22]:
# i can make many operations using numpy library 

array2 = np.array([1, 3, 4, 5, 5, 6, 1, 4, 11, 22,])
print(array2.shape)  # this will print number of elements in the array



(10,)


In [2]:
import numpy as np #impoting numpy and then call it np as short name

In [28]:
# can reshape the arry also

arr = array2.reshape(2,5)  
print(arr)

[[ 1  3  4  5  5]
 [ 6  1  4 11 22]]


In [32]:
# i can create any shape i want before creating it         example

arr2 = np.array([[2, 1, 3], [1, 4, 5], [2, 4, 6], [9, 8, 1]]) 

print(arr2.shape)

[[2 1 3]
 [1 4 5]
 [2 4 6]
 [9 8 1]]
(4, 3)


In [53]:
# if i want to create matrix containing zeros elements then my puting what you want 
allzeros= np.zeros((5, 3))
print(allzeros)

#exple here i can assing one of these index to any value i want
allzeros[3, 2] = 12
print(allzeros)


#also i can create array of ones

ones = np.ones((3, 4))
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. 12.]
 [ 0.  0.  0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
crearray = np.array([[1, 3, 5, 2], [4, 3, 1, 4], [9, 10, 8, 7]])
print(crearray)

print("the shape of the array is :",crearray.shape)  #array shape
print("the dimension of the array is",crearray.ndim)    # here the geting the dimension of the array


[[ 1  3  5  2]
 [ 4  3  1  4]
 [ 9 10  8  7]]
the shape of the array is : (3, 4)
the dimension of the array is 2


In [51]:
#getting the data type of the array
print(crearray.dtype.name)    
print("the size of the array is :", crearray.size) # geting the size of the array

int32
the size of the array is : 12


In [55]:
np.empty((5, 6))    #here is for creating empty array , these value are close to zero

array([[1.03163589e-311, 1.01283457e-321, 0.00000000e+000,
        0.00000000e+000, 7.56599806e-307, 1.16097020e-028],
       [1.26087994e-076, 2.67489366e-028, 3.85216362e-057,
        1.04917183e-153, 5.23081515e-143, 1.18917068e-047],
       [3.69484090e-057, 6.74932338e-067, 4.89034219e-033,
        1.70098498e+256, 5.49109388e-143, 1.06396443e+224],
       [3.96041428e+246, 1.16318408e-028, 1.78577854e-051,
        5.04245242e+174, 2.92868076e-057, 1.85429551e-051],
       [1.01848862e+248, 1.16096643e-028, 9.80058441e+252,
        7.50189709e+247, 1.14484251e+243, 2.59903827e-144]])

In [64]:
np.arange(12, 44, 3)  #it will print numbers between 12 to 44 adding 3 in each time

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [71]:
np.linspace(4,12,15) # this will print 15 numbers from 4 to 12

array([ 4.        ,  4.57142857,  5.14285714,  5.71428571,  6.28571429,
        6.85714286,  7.42857143,  8.        ,  8.57142857,  9.14285714,
        9.71428571, 10.28571429, 10.85714286, 11.42857143, 12.        ])

In [76]:
#numpy for operations
x = np.array([1, 3, 5])
y = np.array([2, 4, 5])

print(x*y)
print(x + y, x-y)
#and so on

[ 2 12 25]
[ 3  7 10] [-1 -1  0]


In [83]:
c = np.array([[2, 3, 4], [4, 1, 6]])

#print(c)

c = c.ravel()  # this will make the 2D into 1D array
print(c)

[2 3 4 4 1 6]


In [87]:
a =np.array([3, 5, 2, 1])
b = np.array([3, 10 , 12, 1])

print(a, b)

a = b

z= b

z [0]= 2

print(a, b, z)
# this will make changes to all index of the all variables because np.array is storing the address of the variabls
#so if change the address then it affect it



[3 5 2 1] [ 3 10 12  1]
[ 2 10 12  1] [ 2 10 12  1] [ 2 10 12  1]


In [91]:
d = a.copy() #you can take copy from another variable
print(d)

[ 2 10 12  1]


In [92]:
a[::-1] # it will reverse the array

array([ 1, 12, 10,  2])

In [93]:
a[:1]  #inclusive and exclusive

array([2])

In [94]:
 a.T  # transpose array

array([ 2, 10, 12,  1])